--- 
- name: install python packages
  become: true
  apt:
    state: latest
    pkg:
      - python-dev
      - python-pip
      - python3-dev
      - python3-pip
  tags:
    - languages
    - python

- name: install python pyenv
  git:
    force: yes
    accept_hostkey: yes
    repo: "https://github.com/pyenv/pyenv.git"
    dest: "{{ lookup('env','HOME') }}/.pyenv"
    version: "master"
  tags:
    - languages
    - python

- name: install python pyenv-virtualenv
  git:
    force: yes
    accept_hostkey: yes
    repo: "https://github.com/pyenv/pyenv-virtualenv.git"
    dest: "{{ lookup('env','HOME') }}/.pyenv/plugins/pyenv-virtualenv"
    version: "master"
  tags:
    - languages
    - python


- name: install python pyenv-virtualenv
  git:
    force: yes
    accept_hostkey: yes
    repo: "https://github.com/pyenv/pyenv-virtualenvwrapper.git"
    dest: "{{ lookup('env','HOME') }}/.pyenv/plugins/pyenv-virtualenvwrapper"
    version: "master"
  tags:
    - languages
    - python

- name: install golang 1.14.3
  become: true
  unarchive:
    src: https://dl.google.com/go/go1.14.3.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
  tags:
    - languages
    - golang

- name: install nim packages
  become: true
  apt:
    state: latest
    pkg:
      - nim
  tags:
    - languages
    - nimlang

- name: install java packages
  become: true
  apt:
    state: latest
    pkg:
      - default-jre
      - default-jdk
  tags:
    - languages
    - java

- name: install java version manager
  git:
    force: yes
    accept_hostkey: yes
    repo: "https://github.com/jenv/jenv.git"
    dest: "{{ lookup('env','HOME') }}/.jenv"
    version: "master"
  tags:
    - languages
    - java