--- 
- name: install python packages
  become: true
  apt:
    state: latest
    pkg:
      - python-dev
      - python-pip
      - python3-dev
      - python3-pip
  tags:
    - languages
    - python

- name: install python pyenv
  git:
    force: yes
    accept_hostkey: yes
    repo: "https://github.com/pyenv/pyenv.git"
    dest: "{{ lookup('env','HOME') }}/.pyenv"
    version: "master"
  tags:
    - languages
    - python

- name: install python pyenv-virtualenv
  git:
    force: yes
    accept_hostkey: yes
    repo: "https://github.com/pyenv/pyenv-virtualenv.git"
    dest: "{{ lookup('env','HOME') }}/.pyenv/plugins/pyenv-virtualenv"
    version: "master"
  tags:
    - languages
    - python


- name: install python pyenv-virtualenv
  git:
    force: yes
    accept_hostkey: yes
    repo: "https://github.com/pyenv/pyenv-virtualenvwrapper.git"
    dest: "{{ lookup('env','HOME') }}/.pyenv/plugins/pyenv-virtualenvwrapper"
    version: "master"
  tags:
    - languages
    - python